spring:
  datasource:
    url: jdbc:h2:mem:finances;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

app:
  ai:
    ollama:
      enabled: true     # keep off while we debug; we’ll re-enable later
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      model: ${OLLAMA_MODEL:llama3.1:8b}
